import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { HelpCircle } from 'lucide-react';
import { useAI } from '../context/AIContext';
export default function PredictiveScoreBadge({ datasetId, versionId, currentScore, proposedFixes = [], className = '' }) {
    const { predictiveScore, isScoreLoading, loadPredictiveScore } = useAI();
    const [showTooltip, setShowTooltip] = useState(false);
    // Load on mount and when fixes change
    const load = () => loadPredictiveScore(datasetId, versionId, proposedFixes);
    return (_jsxs("div", { className: `inline-flex items-center gap-2 ${className}`, children: [isScoreLoading && (_jsxs("span", { className: "inline-flex items-center gap-1 text-xs text-neutral-500", children: [_jsx("span", { className: "w-3 h-3 border-2 border-brass border-t-transparent rounded-full animate-spin" }), "Calculando..."] })), predictiveScore && !isScoreLoading && (_jsxs("div", { className: "inline-flex items-center gap-2 px-2 py-1 bg-neutral-900 border border-neutral-700 rounded-lg", children: [_jsxs("div", { className: "text-right", children: [_jsx("span", { className: "text-2xl font-mono font-bold text-white", children: predictiveScore.predictedScore.toFixed(1) }), _jsx("span", { className: "text-xs text-neutral-500", children: "/100" })] }), _jsxs("div", { className: "flex flex-col items-start gap-1", children: [_jsxs("span", { className: `text-sm font-mono ${predictiveScore.delta > 0 ? 'text-green-400' :
                                    predictiveScore.delta < 0 ? 'text-red-400' : 'text-neutral-500'}`, children: [predictiveScore.delta > 0 ? '+' : '', predictiveScore.delta.toFixed(1)] }), _jsxs("span", { className: "text-[10px] text-neutral-500", children: ["CI: ", predictiveScore.confidenceInterval[0].toFixed(0), "\u2013", predictiveScore.confidenceInterval[1].toFixed(0)] })] }), _jsxs("div", { className: "relative", onMouseEnter: () => setShowTooltip(true), onMouseLeave: () => setShowTooltip(false), children: [_jsx("button", { className: "p-1 text-neutral-500 hover:text-brass transition-colors", "aria-label": "Ver factores", children: _jsx(HelpCircle, { className: "w-4 h-4" }) }), showTooltip && (_jsxs("div", { className: "absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 bg-neutral-900 border border-neutral-700 rounded-lg p-3 text-xs z-50", children: [_jsx("div", { className: "font-medium text-white mb-2", children: "Factores principales:" }), _jsx("ul", { className: "space-y-1", children: predictiveScore.topFeatures.map((f, i) => (_jsxs("li", { className: "flex justify-between text-neutral-300", children: [_jsx("span", { children: f.feature }), _jsxs("span", { className: `font-mono ${f.impact < 0 ? 'text-red-400' : 'text-green-400'}`, children: [f.impact > 0 ? '+' : '', f.impact.toFixed(2)] })] }, i))) })] }))] })] }))] }));
}
